version: "3.8"

services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27317:27017"
    restart: unless-stopped
